### ISSUE TITLE
Add Navigation bar

### ISSUE THREAD

**Issue by omisoul** [omisoul/keepclone#2]
Create the navigation bar to filter various todos

[Preview the navigation bar by clicking the link](https://www.figma.com/file/IU8bFuJulaYta9CKtZMcZe/Keep-Clone-Android-Dev?node-id=8%3A336)

<img width="210" alt="Screenshot 2021-10-12 at 12 45 23 AM" src="https://user-images.githubusercontent.com/31523311/136898431-542a4d16-76b5-4482-bbbf-1ecff1b3131b.png">

**Comment by GLMike** [comment]
I'll attempt this one

**Comment by GLMike** [comment]
So far I have the nav drawer menu designed and ready, current issue is having it show via the button. Working on it now.

**Comment by GLMike** [comment]
Update: I pushed what I did to navbar_implementation branch.

Status of the implementation:
- The navbar is implemented with buttons and such to be used when the rest of the program is implemented.
- The image button for the hamburger button successfully opens the drawer menu.
- I also added a new filter option for "Overdue"

The issue currently: 
- I am unable to link another image button from the nav_header to be used in MainActivity with the intention of closing the drawer menu. As a result, once the drawer menu is opened, it cannot be closed. 
If anyone has any suggestions, please let me know or try to implement it.

Not necessarily an issue:  
- some of the strings for the drawer menu were hardcoded, they should be implemented in the strings.xml instead, will work on it soon.
- The colours of the icons are not showing either the way they were supposed to, but the icons do show up.

A preview of the implementation is attached.
![image_2021-10-13_224240](https://user-images.githubusercontent.com/53978750/137247629-78c73333-567e-4dfb-9019-1e5a96818a9a.png)

**Comment by GLMike** [comment]
Update:
- Managed to get the entire navbar to work now, with thanks to @sadlerb for helping out with suggestions and assisting in implementation.
- The navbar should open once the menu is clicked, and close when you click outside of the menu. 

Here's a preview

https://user-images.githubusercontent.com/53978750/137378552-d15c8895-6b38-4a9c-8913-de2af9b87c99.mp4
