### ISSUE TITLE
Add new Todo

### ISSUE THREAD

**Issue by omisoul** [omisoul/keepclone#3]
Give the user the ability to add a new Todo.

Each Todo should have the following:

1.  Title
2. Category 
3. Due Date
4. Notes (optional)
5. Subtasks (optional)

[Click here to preview the design](https://www.figma.com/file/IU8bFuJulaYta9CKtZMcZe/Keep-Clone-Android-Dev?node-id=3%3A3)

<img width="285" alt="Screenshot 2021-10-12 at 12 46 04 AM" src="https://user-images.githubusercontent.com/31523311/136898485-ad759d7b-0669-4d24-bf0d-ba04bd1507b8.png">

**Comment by sadlerb** [comment]
I can start working on this

**Comment by sadlerb** [comment]
So far most functionality is there. I'm having issues with the spinners though.  The category spinner will show up if clicked and return a value but it's not visible in the menu. The date selector is implemented in a different way than what's designed for now.


All data entered is returned to the main screen after the  add task button is pressed

**Comment by sadlerb** [comment]
Update

Status of the Implementation 

As of the latest commit the user is able to 

- Change the title
- Change the category
- Change the due date
- Add Notes

Current Issues

- Due date selected is not shown
- Subtasks are not fully implemented yet
- If too many subtasks are added, there will be overflow issues

*edit fixed video

https://user-images.githubusercontent.com/55864280/137396077-b0994991-eb9d-454b-aa2a-926ecff83123.mp4
